server:
  port: 80
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - filters:
        - StripPrefix=1
        id: auth
        predicates:
        - Path=/auth/**
        uri: lb://qbc-cloud-auth
      - filters:
        - StripPrefix=1
        - VerifyToken=qbc-cloud-sample-provider
        id: provider
        predicates:
        - Path=/provider/**
        uri: lb://qbc-cloud-sample-provider
      - filters:
        - StripPrefix=1
        id: consumer
        predicates:
        - Path=/consumer/**
        uri: lb://qbc-cloud-sample-consumer